local use_liveupdate = false
--local url = "https://onlinetestcase.com/wp-content/uploads/2023/06"
local url = "http://localhost:8000"
--local filename = "100-KB-OGG.ogg"
local filename = "web/100-KB-WAV.wav"

-- ***************************************************************************
local function play_sound(hash)
	go.set("#music", "sound", hash) -- override the resource data on the component
	sound.play("#music") -- start the playing
end

-- local load_liveupdate(base_url, filename)
-- 
-- 	local lu_callback = function (status, buffer)
--      TODO: Figure out file size!
-- 		-- create a new sound data resource with partial data (allows for streaming)
-- 		-- resource is now owned by the game object
-- 		local hash = resource.create_sound_data(filename .. "c", { data = buffer, partial = true })
-- 		play_sound(hash)
-- 	end
-- 
-- 	resource.load_buffer_async(filename, lu_callback, { offset = 0, size = 16384 }) -- new options table
-- end
-- 


-- ***************************************************************************

local function parse_range(s)
	local _, _, rstart, rend, size = string.find(s, "(%d+)-(%d+)/(%d+)") -- "bytes 0-16383/103277"
	return rstart, rend, size
end

local function http_result(self, _id, response, extra)
	if response.status == 200 or response.status == 206 then
		--pprint(response.headers)
		--pprint(response)
		local relative_path = string.sub(response.url, string.len(url)+1)
		local range = response.headers['content-range'] -- content-range = "bytes 0-16383/103277"
		local rstart, rend, filesize = parse_range(range)
		-- Create the Defold resource, "partial" will enable the streaming mode
		local hash = resource.create_sound_data(relative_path, { data = response.response, filesize = filesize, partial = true })
		-- send "play_sound" to the component
		play_sound(hash)
	end
end

local function load_web_sound(base_url, relative_path)
	local url = base_url .. "/" .. relative_path

	local headers = {}
	headers['Range'] = string.format("bytes=%d-%d", 0, 16384-1)

	http.request(url, "GET", http_result, headers, nil, { ignore_cache = true })
end
-- ***************************************************************************
function init(self)
	url = sys.get_config_string("web.url", url)
	filename = sys.get_config_string("web.filename", filename)
	
	self.initialized = false
	if use_liveupdate then
		liveupdate.add_mount("webmount", url, 100, function ()
				self.initialized = true
			end)
	else
		self.initialized = true
	end

	if use_liveupdate then
		load_liveupdate(url, filename)
	else
		liveupdate.add_mount("webmount", url, 100, function ()
			self.initialized = true

			load_web_sound(url, filename)
		end)
	end
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
